name: fswatch-snap
base: core18
version: '0.1' #
summary: Snap for using fswatch on your host system.
description: |
  fswatch snap for using "fswatch" on your host system. Install as --devmode for now.
  
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  fswatch: #The part where we stage fswatch.
    plugin: nil
    stage-packages:
      - fswatch
      - libfswatch9
apps:
  fswatch:
    command: usr/bin/fswatch
